language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m multi_frame_noise_reduction.test
notifications:
  slack:
    secure: sKG4CZtqoCry02XJ7NUu0PsKvTkzJrUmQs3G5wQUJTcUjsZR7ew4x24mie2+kj9tQqwp35Q2TU6LDE1G2VexzMVhLqne/rXV2vDhZwLTXK4gZ82vb60/N63qnYTVo8cEroUTaWDeAhqlPIJ6740g8drieBXmKMyK5Zgr/WKSTsqFeOwBtqwkdFQOoG+41tyu62THzQFzlRLkvGkMbSN5UcqmL5B/domTV63i0SkR++qAepy2hr19yHwQLRjZ1pnTmoiS54JsXn8UOFMW2jqWiU2NvHgqKQEZJvVzBT2z53uROXrUOPj+GR71RTb9J9evhaCCR4xZuWLJilTcifxskMJ05sMafcASBUETrDe7JU12N675XH0ghBvgI2H1lLUPVPIlbLK1D8XiC7M1thqq3XBPnv5t00RpgwOGPuriQW6orx5y1PzLKyQlR83x3EHldtBdrtHww3Bag3/RUIB8ezJLjFlW8NY1D7AgfeMNAtKZnvk06zSPGZLxNDA0QInV0jn0LJr3X7DJMxXDv2ukAdceA9YWFBEEQ0MpmdZDtUpqfUGHbO8Hot+ZnVhFY89yQoM29/cDdri9YKd6UcPswL0DtkxJaseVLramKWfdU/bzeqAyienhVkjoN69Glcr/bLJvxXPHBOCLfEiQhOTJLnAE6vYVNUNySfXgp98GoBk=
